name: proplus_task
description: "Sign in with GitHub"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_svg: 2.0.9
  dartz: ^0.10.1
  get: ^4.6.6
  intl: ^0.19.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  github_signin_promax: ^0.0.8+1
  firebase_auth: ^5.3.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

dependency_overrides:
  flutter_inappwebview_android:
    git:
      url: https://github.com/holzgeist/flutter_inappwebview
      path: flutter_inappwebview_android
      ref: d89b1d32638b49dfc58c4b7c84153be0c269d057

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/svg_icon/

  fonts:
     - family: Inter
       fonts:
         - asset: assets/fonts/inter/inter_regular.ttf
           weight: 400
         - asset: assets/fonts/inter/inter_medium.ttf
           weight: 500
         - asset: assets/fonts/inter/inter_semiBold.ttf
           weight: 600
         - asset: assets/fonts/inter/inter_bold.ttf
           weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
